---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-secret-store
spec:
  provider:
    vault:
      server: "http://vault-prod-1.vault-prod-1.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "eso-prod-1-role"
          serviceAccountRef:
            name: "eso-sa"
            namespace: "eso-prod-1"
