---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n-prod-1-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas-storage
  local:
    path: /mnt/k8s/n8n-prod-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - k8s-master
              - k8s-node1
              - k8s-node2
