---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-prod-1-dev-software-prod-certificate
  namespace: cert-manager-prod-1
spec:
  secretName: cert-manager-prod-1-dev-software-prod-secret
  issuerRef:
    name: cert-manager-prod-1-letsencrypt-prod-issuer
    kind: Issuer
  commonName: <path:secret/data/cert-manager/prod-1#COMMON_NAME>
  dnsNames: <path:secret/data/cert-manager/prod-1#DOMAINS>
