---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-manager-prod-1-letsencrypt-staging-issuer
  namespace: cert-manager-prod-1
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    avp.kubernetes.io/path: "secret/data/cert-manager/prod-1"
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "<CF_EMAIL>"
    privateKeySecretRef:
      name: cert-manager-prod-1-letsencrypt-staging-issuer
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-token-secret
            key: CF_TOKEN
      selector:
        dnsZones:
          - "dev-software.pl"
