apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager-prod-1-cloudflare-token-secret
  namespace: cert-manager-prod-1
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: cert-manager-prod-1-cloudflare-token-secret
  data:
    - secretKey: cloudflare-token
      remoteRef:
        key: secret/data/cert-manager/prod-1
        property: CF_TOKEN
