---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-credentials
  namespace: cert-manager-prod-1
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "6h" 
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudflare-token-secret
    creationPolicy: Owner
  data:
    - secretKey: CF_TOKEN
      remoteRef:
        key: cert-manager/prod-1
        property: CF_TOKEN
    - secretKey: cloudflare-token
      remoteRef:
        key: cert-manager/prod-1
        property: CF_TOKEN
    - secretKey: CF_EMAIL
      remoteRef:
        key: cert-manager/prod-1
        property: CF_EMAIL
