---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gifto-config
  namespace: gifto-prod-1
data:
  HOSTNAME: "0.0.0.0"
  BASE_URL: "https://gifto.dev-software.pl"
  BETTER_AUTH_URL: "https://gifto.dev-software.pl"
  BETTER_AUTH_CALLBACK_URL: "/families"
