---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gifto-prod-1
  namespace: gifto-prod-1
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  labels:
    app: gifto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gifto
  template:
    metadata:
      labels:
        app: gifto
    spec:
      imagePullSecrets:
        - name: nexus-secret
      initContainers:
      - name: db-migration
        image: nexus3.prod-1.dev-software.pl:5001/gifto/gifto:0.1.1
        imagePullPolicy: Always
        securityContext:
          runAsUser: 0
        envFrom:
          - secretRef:
              name: gifto-secrets
        command:
          - "/bin/sh"
          - "-c"
          - "npm install drizzle-kit && npx drizzle-kit migrate"
      containers:
      - name: gifto
        image: nexus3.prod-1.dev-software.pl:5001/gifto/gifto:0.1.1
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: gifto-secrets
          - configMapRef:
              name: gifto-config
        ports:
        - containerPort: 3000
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
