---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret
  namespace: gifto-prod-1
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "6h" 
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: gifto-secrets
    creationPolicy: Owner
  data:
    - secretKey: BETTER_AUTH_SECRET
      remoteRef:
        key: secret/data/gifto/prod-1
        property: BETTER_AUTH_SECRET
    - secretKey: DB_HOST
      remoteRef:
        key: secret/data/gifto/prod-1
        property: DB_HOST
    - secretKey: DB_NAME
      remoteRef:
        key: secret/data/gifto/prod-1
        property: DB_NAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/data/gifto/prod-1
        property: DB_PASSWORD
    - secretKey: DB_PORT
      remoteRef:
        key: secret/data/gifto/prod-1
        property: DB_PORT
    - secretKey: DB_USER
      remoteRef:
        key: secret/data/gifto/prod-1
        property: DB_USER
