---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gifto-prod-1
resources:
  - ConfigMap.yaml
  - Deployment.yaml
  - ExternalSecrets-nexus.yaml
  - ExternalSecrets.yaml
  - MetricsService.yaml
  - ServiceMonitor.yaml
  - Service.yaml
