---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-prod-1
  namespace: argocd-prod-1
spec:
  project: default
  source:
    repoURL: https://github.com/rafalpo/homelab.git
    targetRevision: master
    path: cert-manager-prod-1
    plugin:
      name: argocd-vault-plugin-helm
  destination:
    namespace: cert-manager-prod-1
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
