---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage
  namespace: argocd-prod-1
spec:
  project: default
  source:
    repoURL: https://github.com/rafalpo/homelab.git
    targetRevision: master
    path: storage
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
