---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-nexus
  namespace: saunamaster-toolbox-prod-1
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "6h" 
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: nexus-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ .url }}": {
                "auth": "{{ printf "%s:%s" .user .password | b64enc }}"
              }
            }
          }
  data:
    - secretKey: url
      remoteRef:
        key: secret/data/nexus-5001
        property: url
    - secretKey: user
      remoteRef:
        key: secret/data/nexus-5001
        property: user
    - secretKey: password
      remoteRef:
        key: secret/data/nexus-5001
        property: password
