---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-backend
  namespace: saunamaster-toolbox-prod-1
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "6h" 
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: backend-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_URL
      remoteRef:
        key: secret/data/saunamaster-toolbox/prod-1
        property: DB_URL
    - secretKey: DB_NAME
      remoteRef:
        key: secret/data/saunamaster-toolbox/prod-1
        property: DB_NAME
    - secretKey: DB_USER
      remoteRef:
        key: secret/data/saunamaster-toolbox/prod-1
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/data/saunamaster-toolbox/prod-1
        property: DB_PASSWORD
