---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-frontend
  namespace: saunamaster-toolbox-prod-1
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "6h" 
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: frontend-secret
    creationPolicy: Owner
  data: []
