---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-vault-0
  namespace: vault-prod-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: nas-storage
  volumeName: vault-prod-1-pv
