---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret
  namespace: sto-prod-1
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "6h" 
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: sto-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/data/sto/prod-1
        property: DB_PASSWORD
    - secretKey: DB_USERNAME
      remoteRef:
        key: secret/data/sto/prod-1
        property: DB_USERNAME
    - secretKey: DB_URL
      remoteRef:
        key: secret/data/sto/prod-1
        property: DB_URL
