---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-token
  namespace: cloudflare-tunnel-prod-1
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 6h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudflared-token-k8s # Nazwa wynikowego Secretu w K8s
    creationPolicy: Owner
  data:
    - secretKey: tunnel-token
      remoteRef:
        key: secret/data/cloudflare-tunnel/prod-1
        property: tunnel-token